blank_issues_enabled: false
contact_links:
  - name: Need Help?
    url: https://github.com/tetarchus/storybook-addon-badges/discussions/new?category=help
    about: Unsure how to achieve something? Start a discussion for support.
