name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - next

jobs:
  test-deploy:
    name: Test Deployments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run tsc && npm run tsc -w docs

      - name: Run Tests
        run: npm run test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Addon
        run: npm run build

      - name: Build Docs
        run: npm run build -w docs
